apiVersion: v2
name: kubequest
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
- name: mysql
  version: "9.3.4"
  repository: "https://charts.bitnami.com/bitnami"
- name: traefik
  version: "26.1.0"
  repository: "https://helm.traefik.io/traefik"
- name: kube-prometheus-stack
  version: "58.0.0"
  repository: "https://prometheus-community.github.io/helm-charts"

