apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-php
  template:
    metadata:
      labels:
        app: app-php
    spec:
      containers:
        - env:
            - name: APP_DEBUG
              value: "true"
            - name: APP_ENV
              value: dev
            - name: APP_KEY
              value: base64:DJYTvaRkEZ/YcQsX3TMpB0iCjgme2rhlIOus9A1hnj4=
            - name: DB_CONNECTION
              value: mysql
            - name: DB_DATABASE
              value: app_database
            - name: DB_HOST
              value: db-service
            - name: DB_PASSWORD
              value: app_password
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: app_user

          image: ghcr.io/k1000kn/sample-app:latest
          imagePullPolicy: IfNotPresent
          name: app
   #       command:
  #          - "sh"
 #           - "-c"
#            - "php artisan migrate && php artisan db:seed && apache2-foreground"
          ports:
            - containerPort: 8081
      restartPolicy: Always
