apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 4
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/sample-app-default: "true"
        io.kompose.service: app
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: app-secret
          image: ghcr.io/k1000kn/sample-app:latest
          name: app
          command:
            - /bin/sh
            - -c
          args:
            - |
              php artisan migrate --force
              php artisan db:seed --force
              apache2-foreground
          ports:
            - containerPort: 80
              hostPort: 8081
              protocol: TCP
          resources: {}
      restartPolicy: Always
