apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db-mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: app_database
            - name: MYSQL_PASSWORD
              value: app_password
            - name: MYSQL_ROOT_PASSWORD
              value: app_root_password
            - name: MYSQL_USER
              value: app_user
          image: mysql:5.7
          name: db
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-data
              subPath: mysql
      restartPolicy: Always
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
