apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: db-storage-class
  hostPath:
    path: /tmp
