apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_DATABASE: YXBwX2RhdGFiYXNl
  MYSQL_PASSWORD: YXBwX3Bhc3N3b3Jk
  MYSQL_ROOT_PASSWORD: YXBwX3Jvb3RfcGFzc3dvcmQ=
  MYSQL_USER: YXBwX3VzZXI=

